---
title: "¡Bienvenidos al Laboratorio de Sistemática y Evolución de Hongos!"
output: 
  html_document:
    toc: FALSE
---

En nuestro equipo nos especializamos en el estudio integral de los hongos, abordando principalmente la sistemática, evolución, diversidad y relaciones ecológicas a través de una aproximación interdisciplinaria que combina la taxonomía clásica, inferencia filogenética, genética de poblaciones, uso de tecnologías de secuenciación de nueva generación y bioinformática. Nuestras investigaciones están orientadas al descubrimiento y descripción de nuevas especies de hongos, así como el estudio de sus interacciones, con un enfoque particular en las especies clavarioides en México. Nuestro equipo está conformado por jóvenes investigadoras e investigadores con experiencia en la ecología y evolución de hongos, comprometidos con la formación de nuevas generaciones de científicos. Si deseas saber más sobre nuestros proyectos, colaboraciones o publicaciones, te invitamos a explorar nuestra página y ponerte en contacto con nosotros.